AllCops:
  Exclude:
    - vendor/**/*
  Include:
    - Gemfile
    - Rakefile
    - bin/*
    - config.ru
    - lib/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Documentation:
  Enabled: false

LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
