AllCops:
  TargetRubyVersion: 2.7
  Include:
    - Gemfile
    - Rakefile
    - bin/*
    - config.ru
    - lib/**/*
  Exclude:
    - vendor/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
