name: Auto Merge
on:
  pull_request:
    branches:
      - master
    types:
      - opened
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependencies/')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: gh pr merge
        run: gh pr merge --auto --merge "${PR_URL}"
