name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
env:
  RUBY_VERSION: '3.1.0'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      # https://github.com/reviewdog/action-rubocop
      - uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          rubocop_version: gemfile
  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: rspec
        run: bundle exec rspec
