name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      ruby_version: ${{ steps.ruby.outputs.version }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      - name: set version
        id: version
        run: |
          version=$(cat .ruby-version)
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
  lint:
    runs-on: ubuntu-latest
    needs:
      - preparation
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ needs.preparation.outputs.ruby_version }}
      # https://github.com/reviewdog/action-rubocop
      - uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          rubocop_version: gemfile
  unit_test:
    runs-on: ubuntu-latest
    needs:
      - preparation
      - lint
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ needs.preparation.outputs.ruby_version }}
      - name: bundle exec rspec
        run: bundle exec rspec
      - name: set coverage
        id: coverage
        run: |
          coverage=$(cat coverage/.last_run.json | jq -r '.result.line')
          echo "coverage=${coverage}" >> "${GITHUB_OUTPUT}"
      # https://github.com/actions/github-script
      - uses: actions/github-script@v5
        env:
          COVERAGE: ${{ steps.coverage.outputs.coverage }}
        with:
          script: |
            const body = `Coverage: ${process.env.COVERAGE}%`

            const options = github.rest.issues.listComments.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })

            const comments = await github.paginate(options)
            const comment = comments.find(c => c.body == body)

            if (comment) {
              return
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            })
