name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/ruby/setup-ruby/releases/tag/v1.229.0
      - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252
        with:
          bundler-cache: true
      # https://github.com/reviewdog/action-rubocop/releases/tag/v2.21.2
      - uses: reviewdog/action-rubocop@fcb74ba274da10b18d038d0bcddaae3518739634
        with:
          reporter: github-pr-review
          rubocop_extensions: rubocop-performance rubocop-rake:gemfile rubocop-rspec:gemfile
          rubocop_version: gemfile
  unit_test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/ruby/setup-ruby/releases/tag/v1.229.0
      - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252
        with:
          bundler-cache: true
      - name: execute rspec
        run: bundle exec rspec
      - name: set coverage
        id: coverage
        run: |
          coverage=$(cat coverage/.last_run.json | jq -r '.result.line')
          echo "coverage=${coverage}" >> "${GITHUB_OUTPUT}"
      # https://github.com/actions/github-script/releases/tag/v7.0.1
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        env:
          COVERAGE: ${{ steps.coverage.outputs.coverage }}
        with:
          script: |
            const body = `Coverage: ${process.env.COVERAGE}%`

            const options = github.rest.issues.listComments.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })

            const comments = await github.paginate(options)
            const comment = comments.find(c => c.body == body)

            if (comment) {
              return
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            })
  security_check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/aquasecurity/trivy-action/releases/tag/0.28.0
      - uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
        with:
          scan-ref: Gemfile.lock
          scan-type: fs
          trivy-config: .trivy.yaml
