name: SBOM
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/aquasecurity/trivy-action
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          format: github
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          output: dependency-results.sbom.json
          scan-ref: Gemfile.lock
          scan-type: fs
          trivy-config: .trivy.yaml
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: ${{ github.workspace }}/dependency-results.sbom.json
          retention-days: 7
